// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/rpki-viz/backend/internal/model"
)

type ASNConnection struct {
	Edges      []*ASNEdge `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type ASNEdge struct {
	Node   *model.ASN `json:"node"`
	Cursor string     `json:"cursor"`
}

type ASNFilter struct {
	Number          *int                   `json:"number,omitempty"`
	Name            *string                `json:"name,omitempty"`
	Country         *string                `json:"country,omitempty"`
	HasROAs         *bool                  `json:"hasROAs,omitempty"`
	HasVRPs         *bool                  `json:"hasVRPs,omitempty"`
	ValidationState *model.ValidationState `json:"validationState,omitempty"`
}

type ASNOrder struct {
	Field     ASNOrderField  `json:"field"`
	Direction OrderDirection `json:"direction"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PrefixConnection struct {
	Edges      []*PrefixEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type PrefixEdge struct {
	Node   *model.Prefix `json:"node"`
	Cursor string        `json:"cursor"`
}

type PrefixFilter struct {
	Cidr            *string                `json:"cidr,omitempty"`
	Asn             *int                   `json:"asn,omitempty"`
	ValidationState *model.ValidationState `json:"validationState,omitempty"`
	HasRoa          *bool                  `json:"hasROA,omitempty"`
	HasVrp          *bool                  `json:"hasVRP,omitempty"`
}

type PrefixOrder struct {
	Field     PrefixOrderField `json:"field"`
	Direction OrderDirection   `json:"direction"`
}

// RPKI Visualization Platform GraphQL Schema
type Query struct {
}

type ROAConnection struct {
	Edges      []*ROAEdge `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type ROAEdge struct {
	Node   *model.ROA `json:"node"`
	Cursor string     `json:"cursor"`
}

type ROAFilter struct {
	Asn     *int    `json:"asn,omitempty"`
	Prefix  *string `json:"prefix,omitempty"`
	Tal     *string `json:"tal,omitempty"`
	IsValid *bool   `json:"isValid,omitempty"`
}

type ROAOrder struct {
	Field     ROAOrderField  `json:"field"`
	Direction OrderDirection `json:"direction"`
}

type VRPConnection struct {
	Edges      []*VRPEdge `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type VRPEdge struct {
	Node   *model.VRP `json:"node"`
	Cursor string     `json:"cursor"`
}

type VRPFilter struct {
	Asn     *int    `json:"asn,omitempty"`
	Prefix  *string `json:"prefix,omitempty"`
	IsValid *bool   `json:"isValid,omitempty"`
}

type VRPOrder struct {
	Field     VRPOrderField  `json:"field"`
	Direction OrderDirection `json:"direction"`
}

type ValidationStats struct {
	Valid    int `json:"valid"`
	Invalid  int `json:"invalid"`
	NotFound int `json:"notFound"`
	Unknown  int `json:"unknown"`
}

// Validity period for ROAs and VRPs
type Validity struct {
	NotBefore time.Time `json:"notBefore"`
	NotAfter  time.Time `json:"notAfter"`
}

type ASNOrderField string

const (
	ASNOrderFieldNumber    ASNOrderField = "NUMBER"
	ASNOrderFieldName      ASNOrderField = "NAME"
	ASNOrderFieldCreatedAt ASNOrderField = "CREATED_AT"
	ASNOrderFieldUpdatedAt ASNOrderField = "UPDATED_AT"
)

var AllASNOrderField = []ASNOrderField{
	ASNOrderFieldNumber,
	ASNOrderFieldName,
	ASNOrderFieldCreatedAt,
	ASNOrderFieldUpdatedAt,
}

func (e ASNOrderField) IsValid() bool {
	switch e {
	case ASNOrderFieldNumber, ASNOrderFieldName, ASNOrderFieldCreatedAt, ASNOrderFieldUpdatedAt:
		return true
	}
	return false
}

func (e ASNOrderField) String() string {
	return string(e)
}

func (e *ASNOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ASNOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ASNOrderField", str)
	}
	return nil
}

func (e ASNOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ASNOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ASNOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PrefixOrderField string

const (
	PrefixOrderFieldCidr            PrefixOrderField = "CIDR"
	PrefixOrderFieldAsn             PrefixOrderField = "ASN"
	PrefixOrderFieldValidationState PrefixOrderField = "VALIDATION_STATE"
	PrefixOrderFieldCreatedAt       PrefixOrderField = "CREATED_AT"
	PrefixOrderFieldUpdatedAt       PrefixOrderField = "UPDATED_AT"
)

var AllPrefixOrderField = []PrefixOrderField{
	PrefixOrderFieldCidr,
	PrefixOrderFieldAsn,
	PrefixOrderFieldValidationState,
	PrefixOrderFieldCreatedAt,
	PrefixOrderFieldUpdatedAt,
}

func (e PrefixOrderField) IsValid() bool {
	switch e {
	case PrefixOrderFieldCidr, PrefixOrderFieldAsn, PrefixOrderFieldValidationState, PrefixOrderFieldCreatedAt, PrefixOrderFieldUpdatedAt:
		return true
	}
	return false
}

func (e PrefixOrderField) String() string {
	return string(e)
}

func (e *PrefixOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PrefixOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PrefixOrderField", str)
	}
	return nil
}

func (e PrefixOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PrefixOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PrefixOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ROAOrderField string

const (
	ROAOrderFieldAsn       ROAOrderField = "ASN"
	ROAOrderFieldPrefix    ROAOrderField = "PREFIX"
	ROAOrderFieldMaxLength ROAOrderField = "MAX_LENGTH"
	ROAOrderFieldCreatedAt ROAOrderField = "CREATED_AT"
	ROAOrderFieldUpdatedAt ROAOrderField = "UPDATED_AT"
)

var AllROAOrderField = []ROAOrderField{
	ROAOrderFieldAsn,
	ROAOrderFieldPrefix,
	ROAOrderFieldMaxLength,
	ROAOrderFieldCreatedAt,
	ROAOrderFieldUpdatedAt,
}

func (e ROAOrderField) IsValid() bool {
	switch e {
	case ROAOrderFieldAsn, ROAOrderFieldPrefix, ROAOrderFieldMaxLength, ROAOrderFieldCreatedAt, ROAOrderFieldUpdatedAt:
		return true
	}
	return false
}

func (e ROAOrderField) String() string {
	return string(e)
}

func (e *ROAOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ROAOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ROAOrderField", str)
	}
	return nil
}

func (e ROAOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ROAOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ROAOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VRPOrderField string

const (
	VRPOrderFieldAsn       VRPOrderField = "ASN"
	VRPOrderFieldPrefix    VRPOrderField = "PREFIX"
	VRPOrderFieldMaxLength VRPOrderField = "MAX_LENGTH"
	VRPOrderFieldCreatedAt VRPOrderField = "CREATED_AT"
	VRPOrderFieldUpdatedAt VRPOrderField = "UPDATED_AT"
)

var AllVRPOrderField = []VRPOrderField{
	VRPOrderFieldAsn,
	VRPOrderFieldPrefix,
	VRPOrderFieldMaxLength,
	VRPOrderFieldCreatedAt,
	VRPOrderFieldUpdatedAt,
}

func (e VRPOrderField) IsValid() bool {
	switch e {
	case VRPOrderFieldAsn, VRPOrderFieldPrefix, VRPOrderFieldMaxLength, VRPOrderFieldCreatedAt, VRPOrderFieldUpdatedAt:
		return true
	}
	return false
}

func (e VRPOrderField) String() string {
	return string(e)
}

func (e *VRPOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VRPOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VRPOrderField", str)
	}
	return nil
}

func (e VRPOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VRPOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VRPOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
