package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"
	"time"

	"github.com/rpki-viz/backend/internal/model"
)

// Prefixes is the resolver for the prefixes field.
func (r *aSNResolver) Prefixes(ctx context.Context, obj *model.ASN) ([]*model.Prefix, error) {
	if obj == nil {
		return nil, fmt.Errorf("ASN object is nil")
	}

	prefixes, err := r.postgresClient.GetPrefixes(ctx, 0, 0, nil, map[string]interface{}{
		"asnId": obj.ID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get prefixes for ASN %s: %w", obj.ID, err)
	}

	return prefixes, nil
}

// Roas is the resolver for the roas field.
func (r *aSNResolver) Roas(ctx context.Context, obj *model.ASN) ([]*model.ROA, error) {
	if obj == nil {
		return nil, fmt.Errorf("ASN object is nil")
	}

	roas, err := r.postgresClient.GetROAsByASN(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get ROAs for ASN %s: %w", obj.ID, err)
	}

	return roas, nil
}

// Vrps is the resolver for the vrps field.
func (r *aSNResolver) Vrps(ctx context.Context, obj *model.ASN) ([]*model.VRP, error) {
	if obj == nil {
		return nil, fmt.Errorf("ASN object is nil")
	}

	vrps, err := r.postgresClient.GetVRPsByASN(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get VRPs for ASN %s: %w", obj.ID, err)
	}

	return vrps, nil
}

// ValidationState is the resolver for the validationState field.
func (r *aSNResolver) ValidationState(ctx context.Context, obj *model.ASN) (model.ValidationState, error) {
	if obj == nil {
		return model.Unknown, fmt.Errorf("ASN object is nil")
	}

	vrps, err := r.postgresClient.GetVRPsByASN(ctx, obj.ID)
	if err != nil {
		return model.Unknown, fmt.Errorf("failed to get VRPs for ASN %s: %w", obj.ID, err)
	}

	if len(vrps) == 0 {
		return model.NotFound, nil
	}

	now := time.Now()
	for _, vrp := range vrps {
		if vrp.NotAfter.After(now) {
			return model.Valid, nil
		}
	}

	return model.Invalid, nil
}

// ValidationStats is the resolver for the validationStats field.
func (r *globalSummaryResolver) ValidationStats(ctx context.Context, obj *model.GlobalSummary) (*ValidationStats, error) {
	if obj == nil {
		return nil, fmt.Errorf("GlobalSummary object is nil")
	}

	return &ValidationStats{
		Valid:    obj.ValidPrefixes,
		Invalid:  obj.InvalidPrefixes,
		NotFound: obj.NotFoundPrefixes,
		Unknown:  obj.TotalPrefixes - obj.ValidPrefixes - obj.InvalidPrefixes - obj.NotFoundPrefixes,
	}, nil
}

// Asn is the resolver for the asn field.
func (r *prefixResolver) Asn(ctx context.Context, obj *model.Prefix) (*model.ASN, error) {
	if obj == nil {
		return nil, fmt.Errorf("Prefix object is nil")
	}

	asn, err := r.postgresClient.GetASNByID(ctx, obj.ASNID)
	if err != nil {
		return nil, fmt.Errorf("failed to get ASN for prefix %s: %w", obj.ID, err)
	}

	return asn, nil
}

// Roa is the resolver for the roa field.
func (r *prefixResolver) Roa(ctx context.Context, obj *model.Prefix) (*model.ROA, error) {
	if obj == nil {
		return nil, fmt.Errorf("Prefix object is nil")
	}

	roas, err := r.postgresClient.GetROAsByPrefix(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get ROAs for prefix %s: %w", obj.ID, err)
	}

	if len(roas) == 0 {
		return nil, nil
	}

	return roas[0], nil
}

// Vrp is the resolver for the vrp field.
func (r *prefixResolver) Vrp(ctx context.Context, obj *model.Prefix) (*model.VRP, error) {
	if obj == nil {
		return nil, fmt.Errorf("Prefix object is nil")
	}

	vrps, err := r.postgresClient.GetVRPsByPrefix(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get VRPs for prefix %s: %w", obj.ID, err)
	}

	if len(vrps) == 0 {
		return nil, nil
	}

	return vrps[0], nil
}

// ValidationState is the resolver for the validationState field.
func (r *prefixResolver) ValidationState(ctx context.Context, obj *model.Prefix) (model.ValidationState, error) {
	if obj == nil {
		return model.Unknown, fmt.Errorf("Prefix object is nil")
	}

	return model.ValidationState(obj.ValidationState), nil
}

// MaxLength is the resolver for the maxLength field.
func (r *prefixResolver) MaxLength(ctx context.Context, obj *model.Prefix) (*int, error) {
	if obj.MaxLength.Valid {
		val := int(obj.MaxLength.Int64)
		return &val, nil
	}
	return nil, nil
}

// ExpiresAt is the resolver for the expiresAt field.
func (r *prefixResolver) ExpiresAt(ctx context.Context, obj *model.Prefix) (*time.Time, error) {
	if obj.ExpiresAt.Valid {
		return &obj.ExpiresAt.Time, nil
	}
	return nil, nil
}

// Asn is the resolver for the asn field.
func (r *queryResolver) Asn(ctx context.Context, number int) (*model.ASN, error) {
	return r.postgresClient.GetASNByNumber(ctx, number)
}

// Asns is the resolver for the asns field.
func (r *queryResolver) Asns(ctx context.Context, first *int, offset *int, orderBy *ASNOrder, filter *ASNFilter) (*ASNConnection, error) {
	// Set defaults
	limit := 20
	off := 0
	if first != nil && *first > 0 {
		limit = *first
	}
	if offset != nil && *offset > 0 {
		off = *offset
	}

	// Convert orderBy to interface{}
	var order interface{}
	if orderBy != nil {
		order = map[string]interface{}{
			"field":     string(orderBy.Field),
			"direction": string(orderBy.Direction),
		}
	}

	// Convert filter to interface{}
	var filterMap interface{}
	if filter != nil {
		fm := make(map[string]interface{})
		if filter.Number != nil {
			fm["number"] = *filter.Number
		}
		if filter.Name != nil {
			fm["name"] = *filter.Name
		}
		if filter.Country != nil {
			fm["country"] = *filter.Country
		}
		filterMap = fm
	}

	asns, err := r.postgresClient.GetASNs(ctx, limit, off, order, filterMap)
	if err != nil {
		return nil, fmt.Errorf("failed to get ASNs: %w", err)
	}

	edges := make([]*ASNEdge, len(asns))
	for i, asn := range asns {
		edges[i] = &ASNEdge{
			Node:   asn,
			Cursor: encodeCursor(asn.ID),
		}
	}

	hasNextPage := len(asns) == limit
	hasPreviousPage := off > 0

	var startCursor, endCursor *string
	if len(edges) > 0 {
		start := edges[0].Cursor
		end := edges[len(edges)-1].Cursor
		startCursor = &start
		endCursor = &end
	}

	return &ASNConnection{
		Edges: edges,
		PageInfo: &PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPreviousPage,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: len(asns),
	}, nil
}

// Prefix is the resolver for the prefix field.
func (r *queryResolver) Prefix(ctx context.Context, cidr string) (*model.Prefix, error) {
	return r.postgresClient.GetPrefixByCIDR(ctx, cidr)
}

// Prefixes is the resolver for the prefixes field.
func (r *queryResolver) Prefixes(ctx context.Context, first *int, offset *int, orderBy *PrefixOrder, filter *PrefixFilter) (*PrefixConnection, error) {
	limit := 20
	off := 0
	if first != nil && *first > 0 {
		limit = *first
	}
	if offset != nil && *offset > 0 {
		off = *offset
	}

	var order interface{}
	if orderBy != nil {
		order = map[string]interface{}{
			"field":     string(orderBy.Field),
			"direction": string(orderBy.Direction),
		}
	}

	var filterMap interface{}
	if filter != nil {
		fm := make(map[string]interface{})
		if filter.Cidr != nil {
			fm["cidr"] = *filter.Cidr
		}
		if filter.Asn != nil {
			asn, err := r.postgresClient.GetASNByNumber(ctx, *filter.Asn)
			if err != nil {
				return nil, fmt.Errorf("failed to get ASN: %w", err)
			}
			if asn != nil {
				fm["asnId"] = asn.ID
			}
		}
		if filter.ValidationState != nil {
			fm["validationState"] = string(*filter.ValidationState)
		}
		filterMap = fm
	}

	prefixes, err := r.postgresClient.GetPrefixes(ctx, limit, off, order, filterMap)
	if err != nil {
		return nil, fmt.Errorf("failed to get prefixes: %w", err)
	}

	edges := make([]*PrefixEdge, len(prefixes))
	for i, prefix := range prefixes {
		edges[i] = &PrefixEdge{
			Node:   prefix,
			Cursor: encodeCursor(prefix.ID),
		}
	}

	hasNextPage := len(prefixes) == limit
	hasPreviousPage := off > 0

	var startCursor, endCursor *string
	if len(edges) > 0 {
		start := edges[0].Cursor
		end := edges[len(edges)-1].Cursor
		startCursor = &start
		endCursor = &end
	}

	return &PrefixConnection{
		Edges: edges,
		PageInfo: &PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPreviousPage,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: len(prefixes),
	}, nil
}

// Roa is the resolver for the roa field.
func (r *queryResolver) Roa(ctx context.Context, id string) (*model.ROA, error) {
	return r.postgresClient.GetROAByID(ctx, id)
}

// Roas is the resolver for the roas field.
func (r *queryResolver) Roas(ctx context.Context, first *int, offset *int, orderBy *ROAOrder, filter *ROAFilter) (*ROAConnection, error) {
	limit := 20
	off := 0
	if first != nil && *first > 0 {
		limit = *first
	}
	if offset != nil && *offset > 0 {
		off = *offset
	}

	var order interface{}
	if orderBy != nil {
		order = map[string]interface{}{
			"field":     string(orderBy.Field),
			"direction": string(orderBy.Direction),
		}
	}

	var filterMap interface{}
	if filter != nil {
		fm := make(map[string]interface{})
		if filter.Asn != nil {
			fm["asn"] = *filter.Asn
		}
		if filter.Prefix != nil {
			fm["prefix"] = *filter.Prefix
		}
		if filter.Tal != nil {
			fm["talId"] = *filter.Tal
		}
		filterMap = fm
	}

	roas, err := r.postgresClient.GetROAs(ctx, limit, off, order, filterMap)
	if err != nil {
		return nil, fmt.Errorf("failed to get ROAs: %w", err)
	}

	edges := make([]*ROAEdge, len(roas))
	for i, roa := range roas {
		edges[i] = &ROAEdge{
			Node:   roa,
			Cursor: encodeCursor(roa.ID),
		}
	}

	hasNextPage := len(roas) == limit
	hasPreviousPage := off > 0

	var startCursor, endCursor *string
	if len(edges) > 0 {
		start := edges[0].Cursor
		end := edges[len(edges)-1].Cursor
		startCursor = &start
		endCursor = &end
	}

	return &ROAConnection{
		Edges: edges,
		PageInfo: &PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPreviousPage,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: len(roas),
	}, nil
}

// Vrp is the resolver for the vrp field.
func (r *queryResolver) Vrp(ctx context.Context, id string) (*model.VRP, error) {
	return r.postgresClient.GetVRPByID(ctx, id)
}

// Vrps is the resolver for the vrps field.
func (r *queryResolver) Vrps(ctx context.Context, first *int, offset *int, orderBy *VRPOrder, filter *VRPFilter) (*VRPConnection, error) {
	limit := 20
	off := 0
	if first != nil && *first > 0 {
		limit = *first
	}
	if offset != nil && *offset > 0 {
		off = *offset
	}

	var order interface{}
	if orderBy != nil {
		order = map[string]interface{}{
			"field":     string(orderBy.Field),
			"direction": string(orderBy.Direction),
		}
	}

	var filterMap interface{}
	if filter != nil {
		fm := make(map[string]interface{})
		if filter.Asn != nil {
			asn, err := r.postgresClient.GetASNByNumber(ctx, *filter.Asn)
			if err != nil {
				return nil, fmt.Errorf("failed to get ASN: %w", err)
			}
			if asn != nil {
				fm["asnId"] = asn.ID
			}
		}
		if filter.Prefix != nil {
			prefix, err := r.postgresClient.GetPrefixByCIDR(ctx, *filter.Prefix)
			if err != nil {
				return nil, fmt.Errorf("failed to get prefix: %w", err)
			}
			if prefix != nil {
				fm["prefixId"] = prefix.ID
			}
		}
		filterMap = fm
	}

	vrps, err := r.postgresClient.GetVRPs(ctx, limit, off, order, filterMap)
	if err != nil {
		return nil, fmt.Errorf("failed to get VRPs: %w", err)
	}

	edges := make([]*VRPEdge, len(vrps))
	for i, vrp := range vrps {
		edges[i] = &VRPEdge{
			Node:   vrp,
			Cursor: encodeCursor(vrp.ID),
		}
	}

	hasNextPage := len(vrps) == limit
	hasPreviousPage := off > 0

	var startCursor, endCursor *string
	if len(edges) > 0 {
		start := edges[0].Cursor
		end := edges[len(edges)-1].Cursor
		startCursor = &start
		endCursor = &end
	}

	return &VRPConnection{
		Edges: edges,
		PageInfo: &PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPreviousPage,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: len(vrps),
	}, nil
}

// TrustAnchor is the resolver for the trustAnchor field.
func (r *queryResolver) TrustAnchor(ctx context.Context, id string) (*model.TrustAnchor, error) {
	return r.postgresClient.GetTrustAnchorByID(ctx, id)
}

// TrustAnchors is the resolver for the trustAnchors field.
func (r *queryResolver) TrustAnchors(ctx context.Context) ([]*model.TrustAnchor, error) {
	return r.postgresClient.GetTrustAnchors(ctx)
}

// GlobalSummary is the resolver for the globalSummary field.
func (r *queryResolver) GlobalSummary(ctx context.Context) (*model.GlobalSummary, error) {
	// Check cache first
	if r.redisClient != nil {
		if cached, err := r.redisClient.GetCachedGlobalSummary(); err == nil && cached != nil {
			if summary, ok := cached.(*model.GlobalSummary); ok {
				return summary, nil
			}
		}
	}

	summary, err := r.postgresClient.GetGlobalSummary(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get global summary: %w", err)
	}

	// Cache the result
	if r.redisClient != nil {
		r.redisClient.CacheGlobalSummary(summary, 5*time.Minute)
	}

	return summary, nil
}

// ValidatePrefix is the resolver for the validatePrefix field.
func (r *queryResolver) ValidatePrefix(ctx context.Context, asn int, prefix string) (*model.ValidationResponse, error) {
	// Check cache first
	if r.redisClient != nil {
		if cached, err := r.redisClient.GetCachedValidationResult(asn, prefix); err == nil && cached != nil {
			if response, ok := cached.(*model.ValidationResponse); ok {
				return response, nil
			}
		}
	}

	// Get ASN to get its ID
	asnModel, err := r.postgresClient.GetASNByNumber(ctx, asn)
	if err != nil {
		return nil, fmt.Errorf("failed to get ASN: %w", err)
	}
	if asnModel == nil {
		return &model.ValidationResponse{
			ASN:    asn,
			Prefix: prefix,
			State:  model.NotFound,
			Reason: "ASN not found",
		}, nil
	}

	// Get prefix to get its ID
	prefixModel, err := r.postgresClient.GetPrefixByCIDR(ctx, prefix)
	if err != nil {
		return nil, fmt.Errorf("failed to get prefix: %w", err)
	}
	if prefixModel == nil {
		return &model.ValidationResponse{
			ASN:    asn,
			Prefix: prefix,
			State:  model.NotFound,
			Reason: "Prefix not found in database",
		}, nil
	}

	// Get all VRPs for this ASN
	vrps, err := r.postgresClient.GetVRPsByASN(ctx, asnModel.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get VRPs for ASN: %w", err)
	}

	result := r.prefixValidator.ValidatePrefix(asn, prefix, vrps)

	response := &model.ValidationResponse{
		ASN:    asn,
		Prefix: prefix,
		State:  result.State,
		Reason: result.Reason,
	}

	// Update the prefix validation state in DB
	if prefixModel != nil {
		err = r.postgresClient.UpdatePrefixValidationState(ctx, prefixModel.ID, result.State)
		if err != nil {
			// Log error but don't fail the response
			fmt.Printf("Failed to update prefix validation state: %v\n", err)
		}
	}

	// Cache the result
	if r.redisClient != nil {
		r.redisClient.CacheValidationResult(asn, prefix, response, 15*time.Minute)
	}

	return response, nil
}

// Asn is the resolver for the asn field.
func (r *rOAResolver) Asn(ctx context.Context, obj *model.ROA) (*model.ASN, error) {
	if obj == nil {
		return nil, fmt.Errorf("ROA object is nil")
	}

	return r.postgresClient.GetASNByID(ctx, obj.ASNID)
}

// Prefix is the resolver for the prefix field.
func (r *rOAResolver) Prefix(ctx context.Context, obj *model.ROA) (*model.Prefix, error) {
	if obj == nil {
		return nil, fmt.Errorf("ROA object is nil")
	}

	return r.postgresClient.GetPrefixByID(ctx, obj.PrefixID)
}

// Validity is the resolver for the validity field.
func (r *rOAResolver) Validity(ctx context.Context, obj *model.ROA) (*Validity, error) {
	if obj == nil {
		return nil, fmt.Errorf("ROA object is nil")
	}

	return &Validity{
		NotBefore: obj.NotBefore,
		NotAfter:  obj.NotAfter,
	}, nil
}

// Certificates is the resolver for the certificates field.
func (r *rOAResolver) Certificates(ctx context.Context, obj *model.ROA) ([]*model.Certificate, error) {
	if obj == nil {
		return nil, fmt.Errorf("ROA object is nil")
	}

	return r.postgresClient.GetCertificatesByROA(ctx, obj.ID)
}

// Tal is the resolver for the tal field.
func (r *rOAResolver) Tal(ctx context.Context, obj *model.ROA) (*model.TrustAnchor, error) {
	if obj == nil {
		return nil, fmt.Errorf("ROA object is nil")
	}

	return r.postgresClient.GetTrustAnchorByID(ctx, obj.TALID)
}

// Certificates is the resolver for the certificates field.
func (r *trustAnchorResolver) Certificates(ctx context.Context, obj *model.TrustAnchor) ([]*model.Certificate, error) {
	if obj == nil {
		return nil, fmt.Errorf("TrustAnchor object is nil")
	}

	return r.postgresClient.GetCertificatesByTrustAnchor(ctx, obj.ID)
}

// Asn is the resolver for the asn field.
func (r *vRPResolver) Asn(ctx context.Context, obj *model.VRP) (*model.ASN, error) {
	if obj == nil {
		return nil, fmt.Errorf("VRP object is nil")
	}

	return r.postgresClient.GetASNByID(ctx, obj.ASNID)
}

// Prefix is the resolver for the prefix field.
func (r *vRPResolver) Prefix(ctx context.Context, obj *model.VRP) (*model.Prefix, error) {
	if obj == nil {
		return nil, fmt.Errorf("VRP object is nil")
	}

	return r.postgresClient.GetPrefixByID(ctx, obj.PrefixID)
}

// Validity is the resolver for the validity field.
func (r *vRPResolver) Validity(ctx context.Context, obj *model.VRP) (*Validity, error) {
	if obj == nil {
		return nil, fmt.Errorf("VRP object is nil")
	}

	return &Validity{
		NotBefore: obj.NotBefore,
		NotAfter:  obj.NotAfter,
	}, nil
}

// Roa is the resolver for the roa field.
func (r *vRPResolver) Roa(ctx context.Context, obj *model.VRP) (*model.ROA, error) {
	if obj == nil {
		return nil, fmt.Errorf("VRP object is nil")
	}

	return r.postgresClient.GetROAByID(ctx, obj.ROAID)
}

// MatchedVRPs is the resolver for the matchedVRPs field.
func (r *validationResponseResolver) MatchedVRPs(ctx context.Context, obj *model.ValidationResponse) ([]*model.VRP, error) {
	if obj == nil {
		return nil, fmt.Errorf("ValidationResponse object is nil")
	}

	// Get ASN by number
	asn, err := r.postgresClient.GetASNByNumber(ctx, obj.ASN)
	if err != nil {
		return nil, fmt.Errorf("failed to get ASN: %w", err)
	}
	if asn == nil {
		return []*model.VRP{}, nil
	}

	// Get prefix by CIDR
	prefix, err := r.postgresClient.GetPrefixByCIDR(ctx, obj.Prefix)
	if err != nil {
		return nil, fmt.Errorf("failed to get prefix: %w", err)
	}
	if prefix == nil {
		return []*model.VRP{}, nil
	}

	// Get VRPs for this ASN and prefix combination
	filterMap := map[string]interface{}{
		"asnId":    asn.ID,
		"prefixId": prefix.ID,
	}

	vrps, err := r.postgresClient.GetVRPs(ctx, 0, 0, nil, filterMap)
	if err != nil {
		return nil, fmt.Errorf("failed to get matched VRPs: %w", err)
	}

	return vrps, nil
}

// ASN returns ASNResolver implementation.
func (r *Resolver) ASN() ASNResolver { return &aSNResolver{r} }

// GlobalSummary returns GlobalSummaryResolver implementation.
func (r *Resolver) GlobalSummary() GlobalSummaryResolver { return &globalSummaryResolver{r} }

// Prefix returns PrefixResolver implementation.
func (r *Resolver) Prefix() PrefixResolver { return &prefixResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// ROA returns ROAResolver implementation.
func (r *Resolver) ROA() ROAResolver { return &rOAResolver{r} }

// TrustAnchor returns TrustAnchorResolver implementation.
func (r *Resolver) TrustAnchor() TrustAnchorResolver { return &trustAnchorResolver{r} }

// VRP returns VRPResolver implementation.
func (r *Resolver) VRP() VRPResolver { return &vRPResolver{r} }

// ValidationResponse returns ValidationResponseResolver implementation.
func (r *Resolver) ValidationResponse() ValidationResponseResolver {
	return &validationResponseResolver{r}
}

type aSNResolver struct{ *Resolver }
type globalSummaryResolver struct{ *Resolver }
type prefixResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type rOAResolver struct{ *Resolver }
type trustAnchorResolver struct{ *Resolver }
type vRPResolver struct{ *Resolver }
type validationResponseResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func encodeCursor(id string) string {
	return base64.StdEncoding.EncodeToString([]byte(id))
}
func decodeCursor(cursor string) (string, error) {
	decoded, err := base64.StdEncoding.DecodeString(cursor)
	if err != nil {
		return "", err
	}
	return string(decoded), nil
}
func parseCursorToOffset(cursor string) (int, error) {
	id, err := decodeCursor(cursor)
	if err != nil {
		return 0, err
	}
	// This is a simple implementation - you might want to store actual offsets
	offset, err := strconv.Atoi(id)
	if err != nil {
		return 0, nil
	}
	return offset, nil
}
